GET http://localhost:3000/prefixo/test

###
GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/4

###
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name":"Categoria teste",
    "description":"descricao teste"
}

###
PATCH http://localhost:3000/categories/4
Content-Type: application/json

{
    "name":"Categoria Update",
    "description":"descricao Update"
}

###
DELETE http://localhost:3000/categories/4
